apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease
  template:
    metadata:
      labels:
        app: heart-disease
    spec:
      containers:
      - name: heart-disease-container
        image: mertmenevse/heart-disease-api:latest
        ports:
        - containerPort: 5000